-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('CountDown_pb')


local COUNTDOWNRES = protobuf.Descriptor();
local COUNTDOWNRES_SECOND_FIELD = protobuf.FieldDescriptor();
local COUNTDOWNRES_GAMETYPE_FIELD = protobuf.FieldDescriptor();

COUNTDOWNRES_SECOND_FIELD.name = "second"
COUNTDOWNRES_SECOND_FIELD.full_name = ".CountDownRes.second"
COUNTDOWNRES_SECOND_FIELD.number = 1
COUNTDOWNRES_SECOND_FIELD.index = 0
COUNTDOWNRES_SECOND_FIELD.label = 1
COUNTDOWNRES_SECOND_FIELD.has_default_value = false
COUNTDOWNRES_SECOND_FIELD.default_value = 0
COUNTDOWNRES_SECOND_FIELD.type = 5
COUNTDOWNRES_SECOND_FIELD.cpp_type = 1

COUNTDOWNRES_GAMETYPE_FIELD.name = "gameType"
COUNTDOWNRES_GAMETYPE_FIELD.full_name = ".CountDownRes.gameType"
COUNTDOWNRES_GAMETYPE_FIELD.number = 2
COUNTDOWNRES_GAMETYPE_FIELD.index = 1
COUNTDOWNRES_GAMETYPE_FIELD.label = 1
COUNTDOWNRES_GAMETYPE_FIELD.has_default_value = false
COUNTDOWNRES_GAMETYPE_FIELD.default_value = 0
COUNTDOWNRES_GAMETYPE_FIELD.type = 5
COUNTDOWNRES_GAMETYPE_FIELD.cpp_type = 1

COUNTDOWNRES.name = "CountDownRes"
COUNTDOWNRES.full_name = ".CountDownRes"
COUNTDOWNRES.nested_types = {}
COUNTDOWNRES.enum_types = {}
COUNTDOWNRES.fields = {COUNTDOWNRES_SECOND_FIELD, COUNTDOWNRES_GAMETYPE_FIELD}
COUNTDOWNRES.is_extendable = false
COUNTDOWNRES.extensions = {}

CountDownRes = protobuf.Message(COUNTDOWNRES)

