-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ErrorCode_pb')


local ERRORCODERES = protobuf.Descriptor();
local ERRORCODERES_ERRORCODE_FIELD = protobuf.FieldDescriptor();

ERRORCODERES_ERRORCODE_FIELD.name = "errorCode"
ERRORCODERES_ERRORCODE_FIELD.full_name = ".ErrorCodeRes.errorCode"
ERRORCODERES_ERRORCODE_FIELD.number = 1
ERRORCODERES_ERRORCODE_FIELD.index = 0
ERRORCODERES_ERRORCODE_FIELD.label = 2
ERRORCODERES_ERRORCODE_FIELD.has_default_value = false
ERRORCODERES_ERRORCODE_FIELD.default_value = 0
ERRORCODERES_ERRORCODE_FIELD.type = 5
ERRORCODERES_ERRORCODE_FIELD.cpp_type = 1

ERRORCODERES.name = "ErrorCodeRes"
ERRORCODERES.full_name = ".ErrorCodeRes"
ERRORCODERES.nested_types = {}
ERRORCODERES.enum_types = {}
ERRORCODERES.fields = {ERRORCODERES_ERRORCODE_FIELD}
ERRORCODERES.is_extendable = false
ERRORCODERES.extensions = {}

ErrorCodeRes = protobuf.Message(ERRORCODERES)

