-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GameStart_pb')


local GAMESTARTRES = protobuf.Descriptor();
local GAMESTARTRES_GAMESTART_FIELD = protobuf.FieldDescriptor();

GAMESTARTRES_GAMESTART_FIELD.name = "gameStart"
GAMESTARTRES_GAMESTART_FIELD.full_name = ".GameStartRes.gameStart"
GAMESTARTRES_GAMESTART_FIELD.number = 1
GAMESTARTRES_GAMESTART_FIELD.index = 0
GAMESTARTRES_GAMESTART_FIELD.label = 1
GAMESTARTRES_GAMESTART_FIELD.has_default_value = false
GAMESTARTRES_GAMESTART_FIELD.default_value = false
GAMESTARTRES_GAMESTART_FIELD.type = 8
GAMESTARTRES_GAMESTART_FIELD.cpp_type = 7

GAMESTARTRES.name = "GameStartRes"
GAMESTARTRES.full_name = ".GameStartRes"
GAMESTARTRES.nested_types = {}
GAMESTARTRES.enum_types = {}
GAMESTARTRES.fields = {GAMESTARTRES_GAMESTART_FIELD}
GAMESTARTRES.is_extendable = false
GAMESTARTRES.extensions = {}

GameStartRes = protobuf.Message(GAMESTARTRES)

