-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('IntTypeReturn_pb')


local INTTYPERETURNRES = protobuf.Descriptor();
local INTTYPERETURNRES_INTVAL_FIELD = protobuf.FieldDescriptor();

INTTYPERETURNRES_INTVAL_FIELD.name = "intVal"
INTTYPERETURNRES_INTVAL_FIELD.full_name = ".IntTypeReturnRes.intVal"
INTTYPERETURNRES_INTVAL_FIELD.number = 1
INTTYPERETURNRES_INTVAL_FIELD.index = 0
INTTYPERETURNRES_INTVAL_FIELD.label = 2
INTTYPERETURNRES_INTVAL_FIELD.has_default_value = false
INTTYPERETURNRES_INTVAL_FIELD.default_value = 0
INTTYPERETURNRES_INTVAL_FIELD.type = 5
INTTYPERETURNRES_INTVAL_FIELD.cpp_type = 1

INTTYPERETURNRES.name = "IntTypeReturnRes"
INTTYPERETURNRES.full_name = ".IntTypeReturnRes"
INTTYPERETURNRES.nested_types = {}
INTTYPERETURNRES.enum_types = {}
INTTYPERETURNRES.fields = {INTTYPERETURNRES_INTVAL_FIELD}
INTTYPERETURNRES.is_extendable = false
INTTYPERETURNRES.extensions = {}

IntTypeReturnRes = protobuf.Message(INTTYPERETURNRES)

