-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Location_pb')


local LOCATIONREQ = protobuf.Descriptor();
local LOCATIONREQ_LOCATIONINFO_FIELD = protobuf.FieldDescriptor();
local LOCATIONINFO = protobuf.Descriptor();
local LOCATIONINFO_ROLEID_FIELD = protobuf.FieldDescriptor();
local LOCATIONINFO_LOCATIONINFO_FIELD = protobuf.FieldDescriptor();
local LOCATIONRES = protobuf.Descriptor();
local LOCATIONRES_INFOS_FIELD = protobuf.FieldDescriptor();

LOCATIONREQ_LOCATIONINFO_FIELD.name = "locationInfo"
LOCATIONREQ_LOCATIONINFO_FIELD.full_name = ".LocationReq.locationInfo"
LOCATIONREQ_LOCATIONINFO_FIELD.number = 1
LOCATIONREQ_LOCATIONINFO_FIELD.index = 0
LOCATIONREQ_LOCATIONINFO_FIELD.label = 1
LOCATIONREQ_LOCATIONINFO_FIELD.has_default_value = false
LOCATIONREQ_LOCATIONINFO_FIELD.default_value = ""
LOCATIONREQ_LOCATIONINFO_FIELD.type = 9
LOCATIONREQ_LOCATIONINFO_FIELD.cpp_type = 9

LOCATIONREQ.name = "LocationReq"
LOCATIONREQ.full_name = ".LocationReq"
LOCATIONREQ.nested_types = {}
LOCATIONREQ.enum_types = {}
LOCATIONREQ.fields = {LOCATIONREQ_LOCATIONINFO_FIELD}
LOCATIONREQ.is_extendable = false
LOCATIONREQ.extensions = {}
LOCATIONINFO_ROLEID_FIELD.name = "roleId"
LOCATIONINFO_ROLEID_FIELD.full_name = ".LocationInfo.roleId"
LOCATIONINFO_ROLEID_FIELD.number = 1
LOCATIONINFO_ROLEID_FIELD.index = 0
LOCATIONINFO_ROLEID_FIELD.label = 1
LOCATIONINFO_ROLEID_FIELD.has_default_value = false
LOCATIONINFO_ROLEID_FIELD.default_value = 0
LOCATIONINFO_ROLEID_FIELD.type = 3
LOCATIONINFO_ROLEID_FIELD.cpp_type = 2

LOCATIONINFO_LOCATIONINFO_FIELD.name = "locationInfo"
LOCATIONINFO_LOCATIONINFO_FIELD.full_name = ".LocationInfo.locationInfo"
LOCATIONINFO_LOCATIONINFO_FIELD.number = 2
LOCATIONINFO_LOCATIONINFO_FIELD.index = 1
LOCATIONINFO_LOCATIONINFO_FIELD.label = 1
LOCATIONINFO_LOCATIONINFO_FIELD.has_default_value = false
LOCATIONINFO_LOCATIONINFO_FIELD.default_value = ""
LOCATIONINFO_LOCATIONINFO_FIELD.type = 9
LOCATIONINFO_LOCATIONINFO_FIELD.cpp_type = 9

LOCATIONINFO.name = "LocationInfo"
LOCATIONINFO.full_name = ".LocationInfo"
LOCATIONINFO.nested_types = {}
LOCATIONINFO.enum_types = {}
LOCATIONINFO.fields = {LOCATIONINFO_ROLEID_FIELD, LOCATIONINFO_LOCATIONINFO_FIELD}
LOCATIONINFO.is_extendable = false
LOCATIONINFO.extensions = {}
LOCATIONRES_INFOS_FIELD.name = "infos"
LOCATIONRES_INFOS_FIELD.full_name = ".LocationRes.infos"
LOCATIONRES_INFOS_FIELD.number = 1
LOCATIONRES_INFOS_FIELD.index = 0
LOCATIONRES_INFOS_FIELD.label = 3
LOCATIONRES_INFOS_FIELD.has_default_value = false
LOCATIONRES_INFOS_FIELD.default_value = {}
LOCATIONRES_INFOS_FIELD.message_type = LOCATIONINFO
LOCATIONRES_INFOS_FIELD.type = 11
LOCATIONRES_INFOS_FIELD.cpp_type = 10

LOCATIONRES.name = "LocationRes"
LOCATIONRES.full_name = ".LocationRes"
LOCATIONRES.nested_types = {}
LOCATIONRES.enum_types = {}
LOCATIONRES.fields = {LOCATIONRES_INFOS_FIELD}
LOCATIONRES.is_extendable = false
LOCATIONRES.extensions = {}

LocationInfo = protobuf.Message(LOCATIONINFO)
LocationReq = protobuf.Message(LOCATIONREQ)
LocationRes = protobuf.Message(LOCATIONRES)

