-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('LongTypeReturn_pb')


local LONGTYPERETURNRES = protobuf.Descriptor();
local LONGTYPERETURNRES_LONGVAL_FIELD = protobuf.FieldDescriptor();

LONGTYPERETURNRES_LONGVAL_FIELD.name = "longVal"
LONGTYPERETURNRES_LONGVAL_FIELD.full_name = ".LongTypeReturnRes.longVal"
LONGTYPERETURNRES_LONGVAL_FIELD.number = 1
LONGTYPERETURNRES_LONGVAL_FIELD.index = 0
LONGTYPERETURNRES_LONGVAL_FIELD.label = 1
LONGTYPERETURNRES_LONGVAL_FIELD.has_default_value = false
LONGTYPERETURNRES_LONGVAL_FIELD.default_value = 0
LONGTYPERETURNRES_LONGVAL_FIELD.type = 3
LONGTYPERETURNRES_LONGVAL_FIELD.cpp_type = 2

LONGTYPERETURNRES.name = "LongTypeReturnRes"
LONGTYPERETURNRES.full_name = ".LongTypeReturnRes"
LONGTYPERETURNRES.nested_types = {}
LONGTYPERETURNRES.enum_types = {}
LONGTYPERETURNRES.fields = {LONGTYPERETURNRES_LONGVAL_FIELD}
LONGTYPERETURNRES.is_extendable = false
LONGTYPERETURNRES.extensions = {}

LongTypeReturnRes = protobuf.Message(LONGTYPERETURNRES)

