//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class weChatFunctionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(weChatFunction), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("QuitGame", QuitGame);
		L.RegFunction("initYunYa", initYunYa);
		L.RegFunction("ImRecordVolume", ImRecordVolume);
		L.RegFunction("YunVaOnLogin", YunVaOnLogin);
		L.RegFunction("yuYinBtnDown", yuYinBtnDown);
		L.RegFunction("yuYinLuZhiDuan", yuYinLuZhiDuan);
		L.RegFunction("yuYinBtnUp", yuYinBtnUp);
		L.RegFunction("yuYinDown", yuYinDown);
		L.RegFunction("getWeChatState", getWeChatState);
		L.RegFunction("weChatLoginGame", weChatLoginGame);
		L.RegFunction("GetDefaultFilePath", GetDefaultFilePath);
		L.RegFunction("ShareBattleBtnClick", ShareBattleBtnClick);
		L.RegFunction("weChatInviteFriendBtnClick", weChatInviteFriendBtnClick);
		L.RegFunction("shareWeChatMomentsBtnClick", shareWeChatMomentsBtnClick);
		L.RegFunction("shareImageWeChatMomentsBtnClick", shareImageWeChatMomentsBtnClick);
		L.RegFunction("GetSprite", GetSprite);
		L.RegFunction("GetDirs", GetDirs);
		L.RegFunction("SetPic", SetPic);
		L.RegFunction("DeleteFolder", DeleteFolder);
		L.RegFunction("openWeChat", openWeChat);
		L.RegFunction("openURL", openURL);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ssdk", get_ssdk, set_ssdk);
		L.RegVar("idfv", get_idfv, set_idfv);
		L.RegVar("filePath", get_filePath, set_filePath);
		L.RegVar("recordPath", get_recordPath, set_recordPath);
		L.RegVar("recordUrlPath", get_recordUrlPath, set_recordUrlPath);
		L.RegVar("isPlay", get_isPlay, set_isPlay);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int QuitGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.QuitGame();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int initYunYa(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			weChatFunction obj = (weChatFunction)ToLua.CheckObject(L, 1, typeof(weChatFunction));
			obj.initYunYa();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ImRecordVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			weChatFunction obj = (weChatFunction)ToLua.CheckObject(L, 1, typeof(weChatFunction));
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.ImRecordVolume(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YunVaOnLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			weChatFunction.YunVaOnLogin(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int yuYinBtnDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.yuYinBtnDown();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int yuYinLuZhiDuan(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			weChatFunction.yuYinLuZhiDuan(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int yuYinBtnUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.yuYinBtnUp();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int yuYinDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			weChatFunction.yuYinDown(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getWeChatState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = weChatFunction.getWeChatState();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int weChatLoginGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.weChatLoginGame();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDefaultFilePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = weChatFunction.GetDefaultFilePath();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareBattleBtnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.ShareBattleBtnClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int weChatInviteFriendBtnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			string arg3 = ToLua.CheckString(L, 4);
			weChatFunction.weChatInviteFriendBtnClick(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int shareWeChatMomentsBtnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			string arg3 = ToLua.CheckString(L, 4);
			weChatFunction.shareWeChatMomentsBtnClick(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int shareImageWeChatMomentsBtnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.shareImageWeChatMomentsBtnClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSprite(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.GameObject));
			UnityEngine.Sprite arg1 = (UnityEngine.Sprite)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Sprite));
			weChatFunction.GetSprite(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDirs(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			weChatFunction.GetDirs(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPic(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.GameObject), typeof(string)))
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.ToObject(L, 1);
				string arg1 = ToLua.ToString(L, 2);
				weChatFunction.SetPic(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.GameObject), typeof(string), typeof(string)))
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.ToObject(L, 1);
				string arg1 = ToLua.ToString(L, 2);
				string arg2 = ToLua.ToString(L, 3);
				weChatFunction.SetPic(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: weChatFunction.SetPic");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DeleteFolder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			weChatFunction.DeleteFolder();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int openWeChat(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			weChatFunction.openWeChat(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int openURL(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			weChatFunction.openURL(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ssdk(IntPtr L)
	{
		try
		{
			ToLua.Push(L, weChatFunction.ssdk);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_idfv(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, weChatFunction.idfv);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_filePath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, weChatFunction.filePath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_recordPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, weChatFunction.recordPath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_recordUrlPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, weChatFunction.recordUrlPath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isPlay(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, weChatFunction.isPlay);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ssdk(IntPtr L)
	{
		try
		{
			cn.sharesdk.unity3d.ShareSDK arg0 = (cn.sharesdk.unity3d.ShareSDK)ToLua.CheckUnityObject(L, 2, typeof(cn.sharesdk.unity3d.ShareSDK));
			weChatFunction.ssdk = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_idfv(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			weChatFunction.idfv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_filePath(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			weChatFunction.filePath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_recordPath(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			weChatFunction.recordPath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_recordUrlPath(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			weChatFunction.recordUrlPath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isPlay(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			weChatFunction.isPlay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

