-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ApplyDisRoomOperate_pb')


local APPLYDISROOMOPERATEREQ = protobuf.Descriptor();
local APPLYDISROOMOPERATEREQ_TYPE_FIELD = protobuf.FieldDescriptor();
local AGREE = protobuf.Descriptor();
local AGREE_ROLEID_FIELD = protobuf.FieldDescriptor();
local DISAGREE = protobuf.Descriptor();
local DISAGREE_CODE_FIELD = protobuf.FieldDescriptor();
local DISAGREE_NAME_FIELD = protobuf.FieldDescriptor();
local ALLAGREE = protobuf.Descriptor();
local ALLAGREE_CODE_FIELD = protobuf.FieldDescriptor();
local ALLAGREE_NAMES_FIELD = protobuf.FieldDescriptor();
local TIMEEND = protobuf.Descriptor();
local TIMEEND_CODE_FIELD = protobuf.FieldDescriptor();
local TIMEEND_ROOMNUM_FIELD = protobuf.FieldDescriptor();
local TIMEEND_MS_FIELD = protobuf.FieldDescriptor();
local APPLYDISROOMOPERATERES = protobuf.Descriptor();
local APPLYDISROOMOPERATERES_TYPE_FIELD = protobuf.FieldDescriptor();
local APPLYDISROOMOPERATERES_DATA_FIELD = protobuf.FieldDescriptor();

APPLYDISROOMOPERATEREQ_TYPE_FIELD.name = "type"
APPLYDISROOMOPERATEREQ_TYPE_FIELD.full_name = ".ApplyDisRoomOperateReq.type"
APPLYDISROOMOPERATEREQ_TYPE_FIELD.number = 1
APPLYDISROOMOPERATEREQ_TYPE_FIELD.index = 0
APPLYDISROOMOPERATEREQ_TYPE_FIELD.label = 2
APPLYDISROOMOPERATEREQ_TYPE_FIELD.has_default_value = false
APPLYDISROOMOPERATEREQ_TYPE_FIELD.default_value = 0
APPLYDISROOMOPERATEREQ_TYPE_FIELD.type = 5
APPLYDISROOMOPERATEREQ_TYPE_FIELD.cpp_type = 1

APPLYDISROOMOPERATEREQ.name = "ApplyDisRoomOperateReq"
APPLYDISROOMOPERATEREQ.full_name = ".ApplyDisRoomOperateReq"
APPLYDISROOMOPERATEREQ.nested_types = {}
APPLYDISROOMOPERATEREQ.enum_types = {}
APPLYDISROOMOPERATEREQ.fields = {APPLYDISROOMOPERATEREQ_TYPE_FIELD}
APPLYDISROOMOPERATEREQ.is_extendable = false
APPLYDISROOMOPERATEREQ.extensions = {}
AGREE_ROLEID_FIELD.name = "roleId"
AGREE_ROLEID_FIELD.full_name = ".Agree.roleId"
AGREE_ROLEID_FIELD.number = 1
AGREE_ROLEID_FIELD.index = 0
AGREE_ROLEID_FIELD.label = 1
AGREE_ROLEID_FIELD.has_default_value = false
AGREE_ROLEID_FIELD.default_value = 0
AGREE_ROLEID_FIELD.type = 3
AGREE_ROLEID_FIELD.cpp_type = 2

AGREE.name = "Agree"
AGREE.full_name = ".Agree"
AGREE.nested_types = {}
AGREE.enum_types = {}
AGREE.fields = {AGREE_ROLEID_FIELD}
AGREE.is_extendable = false
AGREE.extensions = {}
DISAGREE_CODE_FIELD.name = "code"
DISAGREE_CODE_FIELD.full_name = ".DisAgree.code"
DISAGREE_CODE_FIELD.number = 1
DISAGREE_CODE_FIELD.index = 0
DISAGREE_CODE_FIELD.label = 1
DISAGREE_CODE_FIELD.has_default_value = false
DISAGREE_CODE_FIELD.default_value = 0
DISAGREE_CODE_FIELD.type = 5
DISAGREE_CODE_FIELD.cpp_type = 1

DISAGREE_NAME_FIELD.name = "name"
DISAGREE_NAME_FIELD.full_name = ".DisAgree.name"
DISAGREE_NAME_FIELD.number = 2
DISAGREE_NAME_FIELD.index = 1
DISAGREE_NAME_FIELD.label = 1
DISAGREE_NAME_FIELD.has_default_value = false
DISAGREE_NAME_FIELD.default_value = ""
DISAGREE_NAME_FIELD.type = 9
DISAGREE_NAME_FIELD.cpp_type = 9

DISAGREE.name = "DisAgree"
DISAGREE.full_name = ".DisAgree"
DISAGREE.nested_types = {}
DISAGREE.enum_types = {}
DISAGREE.fields = {DISAGREE_CODE_FIELD, DISAGREE_NAME_FIELD}
DISAGREE.is_extendable = false
DISAGREE.extensions = {}
ALLAGREE_CODE_FIELD.name = "code"
ALLAGREE_CODE_FIELD.full_name = ".AllAgree.code"
ALLAGREE_CODE_FIELD.number = 1
ALLAGREE_CODE_FIELD.index = 0
ALLAGREE_CODE_FIELD.label = 1
ALLAGREE_CODE_FIELD.has_default_value = false
ALLAGREE_CODE_FIELD.default_value = 0
ALLAGREE_CODE_FIELD.type = 5
ALLAGREE_CODE_FIELD.cpp_type = 1

ALLAGREE_NAMES_FIELD.name = "names"
ALLAGREE_NAMES_FIELD.full_name = ".AllAgree.names"
ALLAGREE_NAMES_FIELD.number = 2
ALLAGREE_NAMES_FIELD.index = 1
ALLAGREE_NAMES_FIELD.label = 3
ALLAGREE_NAMES_FIELD.has_default_value = false
ALLAGREE_NAMES_FIELD.default_value = {}
ALLAGREE_NAMES_FIELD.type = 9
ALLAGREE_NAMES_FIELD.cpp_type = 9

ALLAGREE.name = "AllAgree"
ALLAGREE.full_name = ".AllAgree"
ALLAGREE.nested_types = {}
ALLAGREE.enum_types = {}
ALLAGREE.fields = {ALLAGREE_CODE_FIELD, ALLAGREE_NAMES_FIELD}
ALLAGREE.is_extendable = false
ALLAGREE.extensions = {}
TIMEEND_CODE_FIELD.name = "code"
TIMEEND_CODE_FIELD.full_name = ".TimeEnd.code"
TIMEEND_CODE_FIELD.number = 1
TIMEEND_CODE_FIELD.index = 0
TIMEEND_CODE_FIELD.label = 1
TIMEEND_CODE_FIELD.has_default_value = false
TIMEEND_CODE_FIELD.default_value = 0
TIMEEND_CODE_FIELD.type = 5
TIMEEND_CODE_FIELD.cpp_type = 1

TIMEEND_ROOMNUM_FIELD.name = "roomNum"
TIMEEND_ROOMNUM_FIELD.full_name = ".TimeEnd.roomNum"
TIMEEND_ROOMNUM_FIELD.number = 2
TIMEEND_ROOMNUM_FIELD.index = 1
TIMEEND_ROOMNUM_FIELD.label = 1
TIMEEND_ROOMNUM_FIELD.has_default_value = false
TIMEEND_ROOMNUM_FIELD.default_value = 0
TIMEEND_ROOMNUM_FIELD.type = 5
TIMEEND_ROOMNUM_FIELD.cpp_type = 1

TIMEEND_MS_FIELD.name = "ms"
TIMEEND_MS_FIELD.full_name = ".TimeEnd.ms"
TIMEEND_MS_FIELD.number = 3
TIMEEND_MS_FIELD.index = 2
TIMEEND_MS_FIELD.label = 1
TIMEEND_MS_FIELD.has_default_value = false
TIMEEND_MS_FIELD.default_value = 0
TIMEEND_MS_FIELD.type = 5
TIMEEND_MS_FIELD.cpp_type = 1

TIMEEND.name = "TimeEnd"
TIMEEND.full_name = ".TimeEnd"
TIMEEND.nested_types = {}
TIMEEND.enum_types = {}
TIMEEND.fields = {TIMEEND_CODE_FIELD, TIMEEND_ROOMNUM_FIELD, TIMEEND_MS_FIELD}
TIMEEND.is_extendable = false
TIMEEND.extensions = {}
APPLYDISROOMOPERATERES_TYPE_FIELD.name = "type"
APPLYDISROOMOPERATERES_TYPE_FIELD.full_name = ".ApplyDisRoomOperateRes.type"
APPLYDISROOMOPERATERES_TYPE_FIELD.number = 1
APPLYDISROOMOPERATERES_TYPE_FIELD.index = 0
APPLYDISROOMOPERATERES_TYPE_FIELD.label = 1
APPLYDISROOMOPERATERES_TYPE_FIELD.has_default_value = false
APPLYDISROOMOPERATERES_TYPE_FIELD.default_value = 0
APPLYDISROOMOPERATERES_TYPE_FIELD.type = 5
APPLYDISROOMOPERATERES_TYPE_FIELD.cpp_type = 1

APPLYDISROOMOPERATERES_DATA_FIELD.name = "data"
APPLYDISROOMOPERATERES_DATA_FIELD.full_name = ".ApplyDisRoomOperateRes.data"
APPLYDISROOMOPERATERES_DATA_FIELD.number = 2
APPLYDISROOMOPERATERES_DATA_FIELD.index = 1
APPLYDISROOMOPERATERES_DATA_FIELD.label = 1
APPLYDISROOMOPERATERES_DATA_FIELD.has_default_value = false
APPLYDISROOMOPERATERES_DATA_FIELD.default_value = ""
APPLYDISROOMOPERATERES_DATA_FIELD.type = 12
APPLYDISROOMOPERATERES_DATA_FIELD.cpp_type = 9

APPLYDISROOMOPERATERES.name = "ApplyDisRoomOperateRes"
APPLYDISROOMOPERATERES.full_name = ".ApplyDisRoomOperateRes"
APPLYDISROOMOPERATERES.nested_types = {}
APPLYDISROOMOPERATERES.enum_types = {}
APPLYDISROOMOPERATERES.fields = {APPLYDISROOMOPERATERES_TYPE_FIELD, APPLYDISROOMOPERATERES_DATA_FIELD}
APPLYDISROOMOPERATERES.is_extendable = false
APPLYDISROOMOPERATERES.extensions = {}

Agree = protobuf.Message(AGREE)
AllAgree = protobuf.Message(ALLAGREE)
ApplyDisRoomOperateReq = protobuf.Message(APPLYDISROOMOPERATEREQ)
ApplyDisRoomOperateRes = protobuf.Message(APPLYDISROOMOPERATERES)
DisAgree = protobuf.Message(DISAGREE)
TimeEnd = protobuf.Message(TIMEEND)

