-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ChessInfo_pb = require("ChessInfo_pb")
module('PlayChess_pb')


local PLAYCHESSREQ = protobuf.Descriptor();
local PLAYCHESSREQ_CHESSID_FIELD = protobuf.FieldDescriptor();
local PLAYCHESSRES = protobuf.Descriptor();
local PLAYCHESSRES_ROLEINDEX_FIELD = protobuf.FieldDescriptor();
local PLAYCHESSRES_CHESSINFO_FIELD = protobuf.FieldDescriptor();

PLAYCHESSREQ_CHESSID_FIELD.name = "chessId"
PLAYCHESSREQ_CHESSID_FIELD.full_name = ".PlayChessReq.chessId"
PLAYCHESSREQ_CHESSID_FIELD.number = 1
PLAYCHESSREQ_CHESSID_FIELD.index = 0
PLAYCHESSREQ_CHESSID_FIELD.label = 2
PLAYCHESSREQ_CHESSID_FIELD.has_default_value = false
PLAYCHESSREQ_CHESSID_FIELD.default_value = 0
PLAYCHESSREQ_CHESSID_FIELD.type = 5
PLAYCHESSREQ_CHESSID_FIELD.cpp_type = 1

PLAYCHESSREQ.name = "PlayChessReq"
PLAYCHESSREQ.full_name = ".PlayChessReq"
PLAYCHESSREQ.nested_types = {}
PLAYCHESSREQ.enum_types = {}
PLAYCHESSREQ.fields = {PLAYCHESSREQ_CHESSID_FIELD}
PLAYCHESSREQ.is_extendable = false
PLAYCHESSREQ.extensions = {}
PLAYCHESSRES_ROLEINDEX_FIELD.name = "roleIndex"
PLAYCHESSRES_ROLEINDEX_FIELD.full_name = ".PlayChessRes.roleIndex"
PLAYCHESSRES_ROLEINDEX_FIELD.number = 1
PLAYCHESSRES_ROLEINDEX_FIELD.index = 0
PLAYCHESSRES_ROLEINDEX_FIELD.label = 1
PLAYCHESSRES_ROLEINDEX_FIELD.has_default_value = false
PLAYCHESSRES_ROLEINDEX_FIELD.default_value = 0
PLAYCHESSRES_ROLEINDEX_FIELD.type = 5
PLAYCHESSRES_ROLEINDEX_FIELD.cpp_type = 1

PLAYCHESSRES_CHESSINFO_FIELD.name = "chessInfo"
PLAYCHESSRES_CHESSINFO_FIELD.full_name = ".PlayChessRes.chessInfo"
PLAYCHESSRES_CHESSINFO_FIELD.number = 2
PLAYCHESSRES_CHESSINFO_FIELD.index = 1
PLAYCHESSRES_CHESSINFO_FIELD.label = 1
PLAYCHESSRES_CHESSINFO_FIELD.has_default_value = false
PLAYCHESSRES_CHESSINFO_FIELD.default_value = nil
PLAYCHESSRES_CHESSINFO_FIELD.message_type = ChessInfo_pb.CHESSINFO
PLAYCHESSRES_CHESSINFO_FIELD.type = 11
PLAYCHESSRES_CHESSINFO_FIELD.cpp_type = 10

PLAYCHESSRES.name = "PlayChessRes"
PLAYCHESSRES.full_name = ".PlayChessRes"
PLAYCHESSRES.nested_types = {}
PLAYCHESSRES.enum_types = {}
PLAYCHESSRES.fields = {PLAYCHESSRES_ROLEINDEX_FIELD, PLAYCHESSRES_CHESSINFO_FIELD}
PLAYCHESSRES.is_extendable = false
PLAYCHESSRES.extensions = {}

PlayChessReq = protobuf.Message(PLAYCHESSREQ)
PlayChessRes = protobuf.Message(PLAYCHESSRES)

