-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PushSign_pb')


local PUSHSIGNRES = protobuf.Descriptor();
local PUSHSIGNRES_SIGNS_FIELD = protobuf.FieldDescriptor();
local PUSHSIGNRES_ROLEID_FIELD = protobuf.FieldDescriptor();

PUSHSIGNRES_SIGNS_FIELD.name = "signs"
PUSHSIGNRES_SIGNS_FIELD.full_name = ".PushSignRes.signs"
PUSHSIGNRES_SIGNS_FIELD.number = 1
PUSHSIGNRES_SIGNS_FIELD.index = 0
PUSHSIGNRES_SIGNS_FIELD.label = 3
PUSHSIGNRES_SIGNS_FIELD.has_default_value = false
PUSHSIGNRES_SIGNS_FIELD.default_value = {}
PUSHSIGNRES_SIGNS_FIELD.type = 5
PUSHSIGNRES_SIGNS_FIELD.cpp_type = 1

PUSHSIGNRES_ROLEID_FIELD.name = "roleId"
PUSHSIGNRES_ROLEID_FIELD.full_name = ".PushSignRes.roleId"
PUSHSIGNRES_ROLEID_FIELD.number = 2
PUSHSIGNRES_ROLEID_FIELD.index = 1
PUSHSIGNRES_ROLEID_FIELD.label = 1
PUSHSIGNRES_ROLEID_FIELD.has_default_value = false
PUSHSIGNRES_ROLEID_FIELD.default_value = 0
PUSHSIGNRES_ROLEID_FIELD.type = 3
PUSHSIGNRES_ROLEID_FIELD.cpp_type = 2

PUSHSIGNRES.name = "PushSignRes"
PUSHSIGNRES.full_name = ".PushSignRes"
PUSHSIGNRES.nested_types = {}
PUSHSIGNRES.enum_types = {}
PUSHSIGNRES.fields = {PUSHSIGNRES_SIGNS_FIELD, PUSHSIGNRES_ROLEID_FIELD}
PUSHSIGNRES.is_extendable = false
PUSHSIGNRES.extensions = {}

PushSignRes = protobuf.Message(PUSHSIGNRES)

