-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('QuitMateRoom_pb')


local QUITMATERES = protobuf.Descriptor();
local QUITMATERES_ROLEID_FIELD = protobuf.FieldDescriptor();

QUITMATERES_ROLEID_FIELD.name = "roleId"
QUITMATERES_ROLEID_FIELD.full_name = ".QuitMateRes.roleId"
QUITMATERES_ROLEID_FIELD.number = 1
QUITMATERES_ROLEID_FIELD.index = 0
QUITMATERES_ROLEID_FIELD.label = 1
QUITMATERES_ROLEID_FIELD.has_default_value = false
QUITMATERES_ROLEID_FIELD.default_value = 0
QUITMATERES_ROLEID_FIELD.type = 5
QUITMATERES_ROLEID_FIELD.cpp_type = 1

QUITMATERES.name = "QuitMateRes"
QUITMATERES.full_name = ".QuitMateRes"
QUITMATERES.nested_types = {}
QUITMATERES.enum_types = {}
QUITMATERES.fields = {QUITMATERES_ROLEID_FIELD}
QUITMATERES.is_extendable = false
QUITMATERES.extensions = {}

QuitMateRes = protobuf.Message(QUITMATERES)

