-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ShareFriendster_pb')


local SHAREFRIENDSTERREQ = protobuf.Descriptor();
local SHAREFRIENDSTERREQ_SHARETYPE_FIELD = protobuf.FieldDescriptor();

SHAREFRIENDSTERREQ_SHARETYPE_FIELD.name = "shareType"
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.full_name = ".ShareFriendsterReq.shareType"
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.number = 1
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.index = 0
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.label = 1
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.has_default_value = false
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.default_value = 0
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.type = 5
SHAREFRIENDSTERREQ_SHARETYPE_FIELD.cpp_type = 1

SHAREFRIENDSTERREQ.name = "ShareFriendsterReq"
SHAREFRIENDSTERREQ.full_name = ".ShareFriendsterReq"
SHAREFRIENDSTERREQ.nested_types = {}
SHAREFRIENDSTERREQ.enum_types = {}
SHAREFRIENDSTERREQ.fields = {SHAREFRIENDSTERREQ_SHARETYPE_FIELD}
SHAREFRIENDSTERREQ.is_extendable = false
SHAREFRIENDSTERREQ.extensions = {}

ShareFriendsterReq = protobuf.Message(SHAREFRIENDSTERREQ)

