-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ShareSign_pb')


local SIGNRES = protobuf.Descriptor();
local SIGNRES_TYPE_FIELD = protobuf.FieldDescriptor();
local SIGNRES_ITEMID_FIELD = protobuf.FieldDescriptor();
local SIGNRES_QUANTITY_FIELD = protobuf.FieldDescriptor();
local SIGNRES_ISSIGN_FIELD = protobuf.FieldDescriptor();
local LUCKDRAW = protobuf.Descriptor();
local LUCKDRAW_TYPE_FIELD = protobuf.FieldDescriptor();
local LUCKDRAW_QUANTITY_FIELD = protobuf.FieldDescriptor();

SIGNRES_TYPE_FIELD.name = "type"
SIGNRES_TYPE_FIELD.full_name = ".SignRes.type"
SIGNRES_TYPE_FIELD.number = 1
SIGNRES_TYPE_FIELD.index = 0
SIGNRES_TYPE_FIELD.label = 1
SIGNRES_TYPE_FIELD.has_default_value = false
SIGNRES_TYPE_FIELD.default_value = 0
SIGNRES_TYPE_FIELD.type = 5
SIGNRES_TYPE_FIELD.cpp_type = 1

SIGNRES_ITEMID_FIELD.name = "itemID"
SIGNRES_ITEMID_FIELD.full_name = ".SignRes.itemID"
SIGNRES_ITEMID_FIELD.number = 2
SIGNRES_ITEMID_FIELD.index = 1
SIGNRES_ITEMID_FIELD.label = 1
SIGNRES_ITEMID_FIELD.has_default_value = false
SIGNRES_ITEMID_FIELD.default_value = 0
SIGNRES_ITEMID_FIELD.type = 5
SIGNRES_ITEMID_FIELD.cpp_type = 1

SIGNRES_QUANTITY_FIELD.name = "quantity"
SIGNRES_QUANTITY_FIELD.full_name = ".SignRes.quantity"
SIGNRES_QUANTITY_FIELD.number = 3
SIGNRES_QUANTITY_FIELD.index = 2
SIGNRES_QUANTITY_FIELD.label = 1
SIGNRES_QUANTITY_FIELD.has_default_value = false
SIGNRES_QUANTITY_FIELD.default_value = 0
SIGNRES_QUANTITY_FIELD.type = 5
SIGNRES_QUANTITY_FIELD.cpp_type = 1

SIGNRES_ISSIGN_FIELD.name = "isSign"
SIGNRES_ISSIGN_FIELD.full_name = ".SignRes.isSign"
SIGNRES_ISSIGN_FIELD.number = 4
SIGNRES_ISSIGN_FIELD.index = 3
SIGNRES_ISSIGN_FIELD.label = 1
SIGNRES_ISSIGN_FIELD.has_default_value = false
SIGNRES_ISSIGN_FIELD.default_value = false
SIGNRES_ISSIGN_FIELD.type = 8
SIGNRES_ISSIGN_FIELD.cpp_type = 7

SIGNRES.name = "SignRes"
SIGNRES.full_name = ".SignRes"
SIGNRES.nested_types = {}
SIGNRES.enum_types = {}
SIGNRES.fields = {SIGNRES_TYPE_FIELD, SIGNRES_ITEMID_FIELD, SIGNRES_QUANTITY_FIELD, SIGNRES_ISSIGN_FIELD}
SIGNRES.is_extendable = false
SIGNRES.extensions = {}
LUCKDRAW_TYPE_FIELD.name = "type"
LUCKDRAW_TYPE_FIELD.full_name = ".LuckDraw.type"
LUCKDRAW_TYPE_FIELD.number = 1
LUCKDRAW_TYPE_FIELD.index = 0
LUCKDRAW_TYPE_FIELD.label = 1
LUCKDRAW_TYPE_FIELD.has_default_value = false
LUCKDRAW_TYPE_FIELD.default_value = 0
LUCKDRAW_TYPE_FIELD.type = 5
LUCKDRAW_TYPE_FIELD.cpp_type = 1

LUCKDRAW_QUANTITY_FIELD.name = "quantity"
LUCKDRAW_QUANTITY_FIELD.full_name = ".LuckDraw.quantity"
LUCKDRAW_QUANTITY_FIELD.number = 2
LUCKDRAW_QUANTITY_FIELD.index = 1
LUCKDRAW_QUANTITY_FIELD.label = 1
LUCKDRAW_QUANTITY_FIELD.has_default_value = false
LUCKDRAW_QUANTITY_FIELD.default_value = 0
LUCKDRAW_QUANTITY_FIELD.type = 5
LUCKDRAW_QUANTITY_FIELD.cpp_type = 1

LUCKDRAW.name = "LuckDraw"
LUCKDRAW.full_name = ".LuckDraw"
LUCKDRAW.nested_types = {}
LUCKDRAW.enum_types = {}
LUCKDRAW.fields = {LUCKDRAW_TYPE_FIELD, LUCKDRAW_QUANTITY_FIELD}
LUCKDRAW.is_extendable = false
LUCKDRAW.extensions = {}

LuckDraw = protobuf.Message(LUCKDRAW)
SignRes = protobuf.Message(SIGNRES)

