-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('StringPara_pb')


local STRINGPARAREQ = protobuf.Descriptor();
local STRINGPARAREQ_VAL_FIELD = protobuf.FieldDescriptor();
local STRINGPARARES = protobuf.Descriptor();
local STRINGPARARES_STRS_FIELD = protobuf.FieldDescriptor();

STRINGPARAREQ_VAL_FIELD.name = "val"
STRINGPARAREQ_VAL_FIELD.full_name = ".StringParaReq.val"
STRINGPARAREQ_VAL_FIELD.number = 1
STRINGPARAREQ_VAL_FIELD.index = 0
STRINGPARAREQ_VAL_FIELD.label = 2
STRINGPARAREQ_VAL_FIELD.has_default_value = false
STRINGPARAREQ_VAL_FIELD.default_value = ""
STRINGPARAREQ_VAL_FIELD.type = 9
STRINGPARAREQ_VAL_FIELD.cpp_type = 9

STRINGPARAREQ.name = "StringParaReq"
STRINGPARAREQ.full_name = ".StringParaReq"
STRINGPARAREQ.nested_types = {}
STRINGPARAREQ.enum_types = {}
STRINGPARAREQ.fields = {STRINGPARAREQ_VAL_FIELD}
STRINGPARAREQ.is_extendable = false
STRINGPARAREQ.extensions = {}
STRINGPARARES_STRS_FIELD.name = "strs"
STRINGPARARES_STRS_FIELD.full_name = ".StringParaRes.strs"
STRINGPARARES_STRS_FIELD.number = 1
STRINGPARARES_STRS_FIELD.index = 0
STRINGPARARES_STRS_FIELD.label = 2
STRINGPARARES_STRS_FIELD.has_default_value = false
STRINGPARARES_STRS_FIELD.default_value = ""
STRINGPARARES_STRS_FIELD.type = 9
STRINGPARARES_STRS_FIELD.cpp_type = 9

STRINGPARARES.name = "StringParaRes"
STRINGPARARES.full_name = ".StringParaRes"
STRINGPARARES.nested_types = {}
STRINGPARARES.enum_types = {}
STRINGPARARES.fields = {STRINGPARARES_STRS_FIELD}
STRINGPARARES.is_extendable = false
STRINGPARARES.extensions = {}

StringParaReq = protobuf.Message(STRINGPARAREQ)
StringParaRes = protobuf.Message(STRINGPARARES)

