-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('VsLog_pb')


local VSLOGREQ = protobuf.Descriptor();
local VSLOGREQ_VSTYPE_FIELD = protobuf.FieldDescriptor();
local VSLOGINFO = protobuf.Descriptor();
local VSLOGINFO_VSTYPE_FIELD = protobuf.FieldDescriptor();
local VSLOGINFO_VSCOUNT_FIELD = protobuf.FieldDescriptor();
local VSLOGINFO_RANK_FIELD = protobuf.FieldDescriptor();
local VSLOGINFO_REWARDCOUNT_FIELD = protobuf.FieldDescriptor();
local VSLOGINFO_VSTIME_FIELD = protobuf.FieldDescriptor();
local VSLOGRES = protobuf.Descriptor();
local VSLOGRES_VSLOGINFO_FIELD = protobuf.FieldDescriptor();

VSLOGREQ_VSTYPE_FIELD.name = "vsType"
VSLOGREQ_VSTYPE_FIELD.full_name = ".VsLogReq.vsType"
VSLOGREQ_VSTYPE_FIELD.number = 1
VSLOGREQ_VSTYPE_FIELD.index = 0
VSLOGREQ_VSTYPE_FIELD.label = 1
VSLOGREQ_VSTYPE_FIELD.has_default_value = false
VSLOGREQ_VSTYPE_FIELD.default_value = 0
VSLOGREQ_VSTYPE_FIELD.type = 5
VSLOGREQ_VSTYPE_FIELD.cpp_type = 1

VSLOGREQ.name = "VsLogReq"
VSLOGREQ.full_name = ".VsLogReq"
VSLOGREQ.nested_types = {}
VSLOGREQ.enum_types = {}
VSLOGREQ.fields = {VSLOGREQ_VSTYPE_FIELD}
VSLOGREQ.is_extendable = false
VSLOGREQ.extensions = {}
VSLOGINFO_VSTYPE_FIELD.name = "vsType"
VSLOGINFO_VSTYPE_FIELD.full_name = ".VsLogInfo.vsType"
VSLOGINFO_VSTYPE_FIELD.number = 1
VSLOGINFO_VSTYPE_FIELD.index = 0
VSLOGINFO_VSTYPE_FIELD.label = 1
VSLOGINFO_VSTYPE_FIELD.has_default_value = false
VSLOGINFO_VSTYPE_FIELD.default_value = 0
VSLOGINFO_VSTYPE_FIELD.type = 5
VSLOGINFO_VSTYPE_FIELD.cpp_type = 1

VSLOGINFO_VSCOUNT_FIELD.name = "vsCount"
VSLOGINFO_VSCOUNT_FIELD.full_name = ".VsLogInfo.vsCount"
VSLOGINFO_VSCOUNT_FIELD.number = 2
VSLOGINFO_VSCOUNT_FIELD.index = 1
VSLOGINFO_VSCOUNT_FIELD.label = 1
VSLOGINFO_VSCOUNT_FIELD.has_default_value = false
VSLOGINFO_VSCOUNT_FIELD.default_value = 0
VSLOGINFO_VSCOUNT_FIELD.type = 5
VSLOGINFO_VSCOUNT_FIELD.cpp_type = 1

VSLOGINFO_RANK_FIELD.name = "rank"
VSLOGINFO_RANK_FIELD.full_name = ".VsLogInfo.rank"
VSLOGINFO_RANK_FIELD.number = 3
VSLOGINFO_RANK_FIELD.index = 2
VSLOGINFO_RANK_FIELD.label = 1
VSLOGINFO_RANK_FIELD.has_default_value = false
VSLOGINFO_RANK_FIELD.default_value = 0
VSLOGINFO_RANK_FIELD.type = 5
VSLOGINFO_RANK_FIELD.cpp_type = 1

VSLOGINFO_REWARDCOUNT_FIELD.name = "rewardCount"
VSLOGINFO_REWARDCOUNT_FIELD.full_name = ".VsLogInfo.rewardCount"
VSLOGINFO_REWARDCOUNT_FIELD.number = 4
VSLOGINFO_REWARDCOUNT_FIELD.index = 3
VSLOGINFO_REWARDCOUNT_FIELD.label = 1
VSLOGINFO_REWARDCOUNT_FIELD.has_default_value = false
VSLOGINFO_REWARDCOUNT_FIELD.default_value = 0
VSLOGINFO_REWARDCOUNT_FIELD.type = 5
VSLOGINFO_REWARDCOUNT_FIELD.cpp_type = 1

VSLOGINFO_VSTIME_FIELD.name = "vsTime"
VSLOGINFO_VSTIME_FIELD.full_name = ".VsLogInfo.vsTime"
VSLOGINFO_VSTIME_FIELD.number = 5
VSLOGINFO_VSTIME_FIELD.index = 4
VSLOGINFO_VSTIME_FIELD.label = 1
VSLOGINFO_VSTIME_FIELD.has_default_value = false
VSLOGINFO_VSTIME_FIELD.default_value = 0
VSLOGINFO_VSTIME_FIELD.type = 3
VSLOGINFO_VSTIME_FIELD.cpp_type = 2

VSLOGINFO.name = "VsLogInfo"
VSLOGINFO.full_name = ".VsLogInfo"
VSLOGINFO.nested_types = {}
VSLOGINFO.enum_types = {}
VSLOGINFO.fields = {VSLOGINFO_VSTYPE_FIELD, VSLOGINFO_VSCOUNT_FIELD, VSLOGINFO_RANK_FIELD, VSLOGINFO_REWARDCOUNT_FIELD, VSLOGINFO_VSTIME_FIELD}
VSLOGINFO.is_extendable = false
VSLOGINFO.extensions = {}
VSLOGRES_VSLOGINFO_FIELD.name = "vsLogInfo"
VSLOGRES_VSLOGINFO_FIELD.full_name = ".VsLogRes.vsLogInfo"
VSLOGRES_VSLOGINFO_FIELD.number = 1
VSLOGRES_VSLOGINFO_FIELD.index = 0
VSLOGRES_VSLOGINFO_FIELD.label = 3
VSLOGRES_VSLOGINFO_FIELD.has_default_value = false
VSLOGRES_VSLOGINFO_FIELD.default_value = {}
VSLOGRES_VSLOGINFO_FIELD.message_type = VSLOGINFO
VSLOGRES_VSLOGINFO_FIELD.type = 11
VSLOGRES_VSLOGINFO_FIELD.cpp_type = 10

VSLOGRES.name = "VsLogRes"
VSLOGRES.full_name = ".VsLogRes"
VSLOGRES.nested_types = {}
VSLOGRES.enum_types = {}
VSLOGRES.fields = {VSLOGRES_VSLOGINFO_FIELD}
VSLOGRES.is_extendable = false
VSLOGRES.extensions = {}

VsLogInfo = protobuf.Message(VSLOGINFO)
VsLogReq = protobuf.Message(VSLOGREQ)
VsLogRes = protobuf.Message(VSLOGRES)

