-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('VsWait_pb')


local VSWAITRES = protobuf.Descriptor();
local VSWAITRES_RANK_FIELD = protobuf.FieldDescriptor();
local VSWAITRES_LEFTROOM_FIELD = protobuf.FieldDescriptor();
local VSWAITRES_CURLUN_FIELD = protobuf.FieldDescriptor();
local VSWAITRES_VSCOUNT_FIELD = protobuf.FieldDescriptor();
local VSWAITRES_VSTYPE_FIELD = protobuf.FieldDescriptor();

VSWAITRES_RANK_FIELD.name = "rank"
VSWAITRES_RANK_FIELD.full_name = ".VsWaitRes.rank"
VSWAITRES_RANK_FIELD.number = 1
VSWAITRES_RANK_FIELD.index = 0
VSWAITRES_RANK_FIELD.label = 1
VSWAITRES_RANK_FIELD.has_default_value = false
VSWAITRES_RANK_FIELD.default_value = 0
VSWAITRES_RANK_FIELD.type = 5
VSWAITRES_RANK_FIELD.cpp_type = 1

VSWAITRES_LEFTROOM_FIELD.name = "leftRoom"
VSWAITRES_LEFTROOM_FIELD.full_name = ".VsWaitRes.leftRoom"
VSWAITRES_LEFTROOM_FIELD.number = 2
VSWAITRES_LEFTROOM_FIELD.index = 1
VSWAITRES_LEFTROOM_FIELD.label = 1
VSWAITRES_LEFTROOM_FIELD.has_default_value = false
VSWAITRES_LEFTROOM_FIELD.default_value = 0
VSWAITRES_LEFTROOM_FIELD.type = 5
VSWAITRES_LEFTROOM_FIELD.cpp_type = 1

VSWAITRES_CURLUN_FIELD.name = "curLun"
VSWAITRES_CURLUN_FIELD.full_name = ".VsWaitRes.curLun"
VSWAITRES_CURLUN_FIELD.number = 3
VSWAITRES_CURLUN_FIELD.index = 2
VSWAITRES_CURLUN_FIELD.label = 1
VSWAITRES_CURLUN_FIELD.has_default_value = false
VSWAITRES_CURLUN_FIELD.default_value = 0
VSWAITRES_CURLUN_FIELD.type = 5
VSWAITRES_CURLUN_FIELD.cpp_type = 1

VSWAITRES_VSCOUNT_FIELD.name = "vsCount"
VSWAITRES_VSCOUNT_FIELD.full_name = ".VsWaitRes.vsCount"
VSWAITRES_VSCOUNT_FIELD.number = 4
VSWAITRES_VSCOUNT_FIELD.index = 3
VSWAITRES_VSCOUNT_FIELD.label = 1
VSWAITRES_VSCOUNT_FIELD.has_default_value = false
VSWAITRES_VSCOUNT_FIELD.default_value = 0
VSWAITRES_VSCOUNT_FIELD.type = 5
VSWAITRES_VSCOUNT_FIELD.cpp_type = 1

VSWAITRES_VSTYPE_FIELD.name = "vsType"
VSWAITRES_VSTYPE_FIELD.full_name = ".VsWaitRes.vsType"
VSWAITRES_VSTYPE_FIELD.number = 5
VSWAITRES_VSTYPE_FIELD.index = 4
VSWAITRES_VSTYPE_FIELD.label = 1
VSWAITRES_VSTYPE_FIELD.has_default_value = false
VSWAITRES_VSTYPE_FIELD.default_value = 0
VSWAITRES_VSTYPE_FIELD.type = 5
VSWAITRES_VSTYPE_FIELD.cpp_type = 1

VSWAITRES.name = "VsWaitRes"
VSWAITRES.full_name = ".VsWaitRes"
VSWAITRES.nested_types = {}
VSWAITRES.enum_types = {}
VSWAITRES.fields = {VSWAITRES_RANK_FIELD, VSWAITRES_LEFTROOM_FIELD, VSWAITRES_CURLUN_FIELD, VSWAITRES_VSCOUNT_FIELD, VSWAITRES_VSTYPE_FIELD}
VSWAITRES.is_extendable = false
VSWAITRES.extensions = {}

VsWaitRes = protobuf.Message(VSWAITRES)

