--GPS界面
GPSInfoPanel = {
}

setbaseclass(GPSInfoPanel, {BasePanel})

function GPSInfoPanel:InitPanel()
	self.btnClose 		= self:Child("btnClose")
	self.btnDisslution	= self:Child("imgBg/btnDisslution")
	self.btnContinue	= self:Child("imgBg/btnContinue")
    self.G2 			= self:Child("imgBg/G2")
    self.G3 			= self:Child("imgBg/G3")
    self.G4 			= self:Child("imgBg/G4")
    self.G5 			= self:Child("imgBg/G5")

    self.imgHead1 		= self:Child("imgBg/imgHead1")
    self.txtOpen1		= self:Child("imgBg/imgHead1/txtOff")
    self.imgHead2 		= self:Child("imgBg/imgHead2")
    self.txtOpen2		= self:Child("imgBg/imgHead2/txtOff")
    self.imgHead3 		= self:Child("imgBg/imgHead3")
    self.txtOpen3		= self:Child("imgBg/imgHead3/txtOff")
    self.imgHead4 		= self:Child("imgBg/imgHead4")
    self.txtOpen4		= self:Child("imgBg/imgHead4/txtOff")
    self.imgHead5 		= self:Child("imgBg/imgHead5")
    self.txtOpen5		= self:Child("imgBg/imgHead5/txtOff")

    self.txtTips 		= self:Child("imgBg/txtTips")

    self.G2line12		= self:Child("imgBg/G2/line")
    self.G2txt12		= self:Child("imgBg/G2/txt12")

    self.G3line12		= self:Child("imgBg/G3/line12")
    self.G3line13		= self:Child("imgBg/G3/line13")
    self.G3line23		= self:Child("imgBg/G3/line23")
    self.G3txt12		= self:Child("imgBg/G3/txt12")
    self.G3txt13		= self:Child("imgBg/G3/txt13")
    self.G3txt23		= self:Child("imgBg/G3/txt23")

    self.G4line12		= self:Child("imgBg/G4/line12")
    self.G4line13		= self:Child("imgBg/G4/line13")
    self.G4line14		= self:Child("imgBg/G4/line14")
    self.G4line23		= self:Child("imgBg/G4/line23")
    self.G4line24		= self:Child("imgBg/G4/line24")
    self.G4line34		= self:Child("imgBg/G4/line34")
    self.G4txt12		= self:Child("imgBg/G4/txt12")
    self.G4txt13		= self:Child("imgBg/G4/txt13")
    self.G4txt14		= self:Child("imgBg/G4/txt14")
    self.G4txt23		= self:Child("imgBg/G4/txt23")
    self.G4txt24		= self:Child("imgBg/G4/txt24")
    self.G4txt34		= self:Child("imgBg/G4/txt34")

    self.G5line12		= self:Child("imgBg/G5/line12")
    self.G5line13		= self:Child("imgBg/G5/line13")
    self.G5line14		= self:Child("imgBg/G5/line14")
    self.G5line15		= self:Child("imgBg/G5/line15")
    self.G5line23		= self:Child("imgBg/G5/line23")
    self.G5line24		= self:Child("imgBg/G5/line24")
    self.G5line25		= self:Child("imgBg/G5/line25")
    self.G5line34		= self:Child("imgBg/G5/line34")
    self.G5line35		= self:Child("imgBg/G5/line35")
    self.G5line45		= self:Child("imgBg/G5/line45")
    self.G5txt12		= self:Child("imgBg/G5/txt12")
    self.G5txt13		= self:Child("imgBg/G5/txt13")
    self.G5txt14		= self:Child("imgBg/G5/txt14")
    self.G5txt15		= self:Child("imgBg/G5/txt15")
    self.G5txt23		= self:Child("imgBg/G5/txt23")
    self.G5txt24		= self:Child("imgBg/G5/txt24")
    self.G5txt25		= self:Child("imgBg/G5/txt25")
    self.G5txt34		= self:Child("imgBg/G5/txt34")
    self.G5txt35		= self:Child("imgBg/G5/txt35")
    self.G5txt45		= self:Child("imgBg/G5/txt45")

    self.imgRed         = self:Child("imgBg/imgRed") 
    self.imgGreen       = self:Child("imgBg/imgGreen")
end