
-- 主打牌界面
TH_GameMainPanel = {
}

setbaseclass(TH_GameMainPanel, { BasePanel })

function TH_GameMainPanel:InitPanel()
	-- 好友等待
	self.imgHTWaitFriends = self:Child("imgHTWaitFriends")
	self.btnInvitationWeChat = self:Child("imgHTWaitFriends/btnInvitationWeChat")
	self.btnGameStart = self:Child("imgHTWaitFriends/btnGameStart")
	self.btnPrepareButton = self:Child("btnprepareButton")
	self.btnFuZhiRoomNum = self:Child("imgHTWaitFriends/btnFuZhiRoomNum")
	-- 复制房间号
	-- 十点半战斗主界面
	self.imgHTGameMain = self:Child("imgHTGameMain")
	self.imgFenShu = self:Child("imgHTGameMain/imgFenShu")
	self.btn5FenG = self:Child("imgHTGameMain/imgFenShu/btn5FenG")
	self.btn8Fen = self:Child("imgHTGameMain/imgFenShu/btn8Fen")
	self.btn10Fen = self:Child("imgHTGameMain/imgFenShu/btn10Fen")
	self.btn15Fen = self:Child("imgHTGameMain/imgFenShu/btn15Fen")

	self.imgFenShu2 = self:Child("imgHTGameMain/imgFenShu2")
	self.btn2Fen = self:Child("imgHTGameMain/imgFenShu2/btn2Fen")
	self.btn3Fen = self:Child("imgHTGameMain/imgFenShu2/btn3Fen")
	self.btn4Fen = self:Child("imgHTGameMain/imgFenShu2/btn4Fen")
	self.btn5FenD = self:Child("imgHTGameMain/imgFenShu2/btn5FenD")

	self.imgIsBuPai = self:Child("imgHTGameMain/imgIsBuPai")
	self.btnBuBuPai = self:Child("imgHTGameMain/imgIsBuPai/btnBuBuPai")
	self.btnBuPai = self:Child("imgHTGameMain/imgIsBuPai/btnBuPai")
	self.btnKaiPai = self:Child("imgHTGameMain/imgIsBuPai/btnKaiPai")

	self.btnVSCard = self:Child("imgHTGameMain/btnVSCard")

	self.imgIsDangZhuang = self:Child("imgHTGameMain/imgIsDangZhuang")
	self.btnBuDang = self:Child("imgHTGameMain/imgIsDangZhuang/btnBuDang")
	self.btnDang = self:Child("imgHTGameMain/imgIsDangZhuang/btnDang")

	self.imgIsQiangZhuang = self:Child("imgHTGameMain/imgIsQiangZhuang")
	self.btnBuQiang = self:Child("imgHTGameMain/imgIsQiangZhuang/btnBuQiang")
	self.btnQiang = self:Child("imgHTGameMain/imgIsQiangZhuang/btnQiang")

	-- 金花战斗主界面
	self.imgJHGameMain = self:Child("imgJHGameMain")
	self.imgJHBeishu = self:Child("imgJHGameMain/imgBeishu")
	self.btnJHUnDouble = self:Child("imgJHGameMain/imgBeishu/btnUnDouble")
	self.btnJH2Bei = self:Child("imgJHGameMain/imgBeishu/btn2Bei")
	self.btnJH3Bei = self:Child("imgJHGameMain/imgBeishu/btn3Bei")
	self.btnJH4Bei = self:Child("imgJHGameMain/imgBeishu/btn4Bei")
	self.btnJH5Bei = self:Child("imgJHGameMain/imgBeishu/btn5Bei")

	self.imgFace = self:Child("imgJHGameMain/imgLoseAnim")
	self.imgJHCompareOrBet = self:Child("imgJHGameMain/imgCompareOrBet")
	self.btnJHQiPai = self:Child("imgJHGameMain/imgCompareOrBet/btnQiPai")
	self.btnJHBiPai = self:Child("imgJHGameMain/imgCompareOrBet/btnBiPai")
	self.btnJHJiaZhu = self:Child("imgJHGameMain/imgCompareOrBet/btnJiaZhu")
	self.btnJHGengZhu = self:Child("imgJHGameMain/imgCompareOrBet/btnGengZhu")
	self.txtCurBet = self:Child("imgJHGameMain/txtCurBet")
	self.btnBack = self:Child("imgJHGameMain/btnBack")

	self.imgVsShow = self:Child("imgJHGameMain/imgVsShow")
	self.imgVleft = self:Child("imgJHGameMain/imgVsShow/img_v_left")
	self.imgSright = self:Child("imgJHGameMain/imgVsShow/img_s_right")
	self.imgVsLight = self:Child("imgJHGameMain/imgVsShow/imgVsLight")

	self.Lhead = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/Mask/img")
	self.LtxtScore = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/txtScore")
	self.LtxtName = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/txtName")
	self.Limg1 = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/imgCard/Image1")
	self.Limg2 = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/imgCard/Image2")
	self.Limg3 = self:Child("imgJHGameMain/imgVsShow/img_v_left/imgVL/imgCard/Image3")

	self.Rhead = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/Mask/img")
	self.RtxtScore = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/txtScore")
	self.RtxtName = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/txtName")
	self.Rimg1 = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/imgCard/Image1")
	self.Rimg2 = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/imgCard/Image2")
	self.Rimg3 = self:Child("imgJHGameMain/imgVsShow/img_s_right/imgVR/imgCard/Image3")
	self.imgBoom = self:Child("imgJHGameMain/imgVsShow/imgBoom")

	self.cardth = self:Child("cardList/card_th")
	self.cardthone = self:Child("cardList/card_thone")
	self.cardjh = self:Child("cardList/card_jh")
	self.cardjhone = self:Child("cardList/card_jhone")
	self.cardnn = self:Child("cardList/card_nn")
	self.cardnnone = self:Child("cardList/card_nnone")
	self.btn_gray = self:Child("cardList/btn_gray")
	self.card_gray = self:Child("cardList/card_gray")
	self.betList = self:Child("betList")

	self.imgLoseAnim = self:Child("imgJHGameMain/imgLoseAnim")
	self.btnLoseAnim1 = self:Child("imgJHGameMain/imgLoseAnim/imgBg1/Anim1")
	self.btnLoseAnim2 = self:Child("imgJHGameMain/imgLoseAnim/imgBg2/Anim2")
	self.btnLoseAnim3 = self:Child("imgJHGameMain/imgLoseAnim/imgBg3/Anim3")
	self.btnLoseAnim4 = self:Child("imgJHGameMain/imgLoseAnim/imgBg4/Anim4")
	self.btnLoseAnim5 = self:Child("imgJHGameMain/imgLoseAnim/imgBg5/Anim5")
	self.btnLoseAnim6 = self:Child("imgJHGameMain/imgLoseAnim/imgBg6/Anim6")

	self.imgBaoZi = self:Child("jinhuaList/baozi")
	self.imgJinHua = self:Child("jinhuaList/jinhua")
	self.imgShunJin = self:Child("jinhuaList/shunjin")
	self.imgShunZi = self:Child("jinhuaList/shunzi")


	-- 每局结算
	self.imgHTSingleSettlement = self:Child("imgHTSingleSettlement")
	self.imgSettlementWin = self:Child("imgHTSingleSettlement/imgSettlementWin")
	self.imgSettlementLost = self:Child("imgHTSingleSettlement/imgSettlementLost")
	self.btnSettleStartGame = self:Child("imgHTSingleSettlement/BottomBtn/btnSettleStartGame")
	self.txtLose = self:Child("imgHTSingleSettlement/txtLose")
	self.txtWin = self:Child("imgHTSingleSettlement/txtWin")
	-- 新添加
	self.btnSettleQuitGame = self:Child("imgHTSingleSettlement/BottomBtn/btnSettleQuitGame")

	-- 牛牛界面
	self.img0 = self:Child("niuniuList/n0")
	self.img1 = self:Child("niuniuList/n1")
	self.img2 = self:Child("niuniuList/n2")
	self.img3 = self:Child("niuniuList/n3")
	self.img4 = self:Child("niuniuList/n4")
	self.img5 = self:Child("niuniuList/n5")
	self.img6 = self:Child("niuniuList/n6")
	self.img7 = self:Child("niuniuList/n7")
	self.img8 = self:Child("niuniuList/n8")
	self.img9 = self:Child("niuniuList/n9")
	self.img10 = self:Child("niuniuList/n10")
	self.img11 = self:Child("niuniuList/n11")
	self.img12 = self:Child("niuniuList/n12")
	self.img13 = self:Child("niuniuList/n13")
	self.img14 = self:Child("niuniuList/n14")
	self.img15 = self:Child("niuniuList/n15")
	self.img16 = self:Child("niuniuList/n16")
	self.img17 = self:Child("niuniuList/n17")

	self.bet1 = self:Child("niubetList/c1")
	self.bet2 = self:Child("niubetList/c2")
	self.bet3 = self:Child("niubetList/c3")
	self.bet4 = self:Child("niubetList/c4")

	self.imgNiuWin = self:Child("imgHTSingleSettlement/imgNiuWin")
	self.imgNiuLose = self:Child("imgHTSingleSettlement/imgNiuLose")
	self.imgNNGameMain = self:Child("imgNNGameMain")
	self.btnHintCard = self:Child("imgNNGameMain/imgIsBuPai/btnHintCard")
	self.btnShowPai = self:Child("imgNNGameMain/imgIsBuPai/btnShowPai")
	self.txtShowPai = self:Child("imgNNGameMain/imgIsBuPai/btnShowPai/Text")
	self.btnHuanPai = self:Child("imgNNGameMain/imgIsBuPai/btnHuanPai")
	self.btnBuHuan = self:Child("imgNNGameMain/imgIsBuPai/btnBuHuan")
	self.imgBeiShu = self:Child("imgNNGameMain/imgBeiShu")
	self.btnTitle = self:Child("imgNNGameMain/imgBeiShu/btnTitle")
	self.btnNotBet = self:Child("imgNNGameMain/imgBeiShu/btnTitle/btnNotBet")
	self.btnQ1 = self:Child("imgNNGameMain/imgBeiShu/btnTitle/btnQ1")
	self.btnQ2 = self:Child("imgNNGameMain/imgBeiShu/btnTitle/btnQ2")
	self.btnQ3 = self:Child("imgNNGameMain/imgBeiShu/btnTitle/btnQ3")
	self.btnQ4 = self:Child("imgNNGameMain/imgBeiShu/btnTitle/btnQ4")

	self.btnBet = self:Child("imgNNGameMain/imgBeiShu/btnBet")
	self.btn1 = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn1")
	self.btn1txt = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn1/Text")
	self.btn2 = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn2")
	self.btn2txt = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn2/Text")
	self.btn3 = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn3")
	self.btn3txt = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn3/Text")
	self.btn4 = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn4")
	self.btn4txt = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn4/Text")
	self.btn5 = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn5")
	self.btn5txt = self:Child("imgNNGameMain/imgBeiShu/btnBet/btn5/Text")

	self.imgClock = self:Child("imgClock")
	self.txtClock = self:Child("imgClock/textClock")
	self.txtRoomChange = self:Child("imgClock/txtRoomChange")
	self.objN1 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card1")
	self.objN2 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card2")
	self.objN3 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card3")
	self.objN4 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card4")
	self.objN5 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card5")
	self.objN6 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card6")
	self.objN7 = self:Child("imgShowTips/niuniuTip/Viewport/Content/card7")
	-- 公用
	self.btnQuitRoom = self:Child("btnQuitRoom")
	self.btnTalk = self:Child("btnTalk")
	self.imgTips = self:Child("imgTips")
	self.imgPublicCard = self:Child("imgPublicCard")
	self.btnGPS = self:Child("btnGPS")
	self.btnChat = self:Child("btnChat")
	self.imgQuitTips = self:Child("QuitGameTips")
	self.txtQuitTips = self:Child("QuitGameTips/txtMessageTips")
	self.btnQuitTipsYes = self:Child("QuitGameTips/btnSure")
	self.btnQuitTipsNo = self:Child("QuitGameTips/btnRefuse")
	self.imgAnimList = self:Child("imgAnimList")
	self.imgSignalBG = self:Child("imgSignalBG")
	self.txtTime = self:Child("imgSignalBG/txtTime")
	self.imgSignal1 = self:Child("imgSignalBG/imgSignal1")
	self.imgSignal2 = self:Child("imgSignalBG/imgSignal2")
	self.imgSignal3 = self:Child("imgSignalBG/imgSignal3")
	self.imgSignal4 = self:Child("imgSignalBG/imgSignal4")
	self.imgSignal5 = self:Child("imgSignalBG/imgSignal5")
	self.inputSendCode = self:Child("inputSendCode")
	self.btnSendCode = self:Child("btnSendCode")
	-- 提示
	self.imgShowTips = self:Child("imgShowTips")
	self.btnClose = self:Child("imgShowTips/btnClose")
	self.jinhuaTip = self:Child("imgShowTips/jinhuaTip")
	self.shidianbanTip = self:Child("imgShowTips/shidianbanTip")
	self.niuniuTip = self:Child("imgShowTips/niuniuTip")
	self.btnGouwuche = self:Child("btnGouwuche")

	-- GameSetting Panel
	self.PanelGameSetting = self:Child("PanelGameSetting")
	self.QuitHideButton = self:Child("PanelGameSetting/QuitHideButton")
	self.imgNotWaitQuitRoom = self:Child("PanelGameSetting/imgHideBg/imgNotWaitQuitRoom")
	self.btnWaitQuitRoom = self:Child("PanelGameSetting/imgHideBg/btnWaitQuitRoom")
	self.imgNotGameMainQuitRoom = self:Child("PanelGameSetting/imgHideBg/imgNotGameMainQuitRoom")
	self.btnGameMainQuitRoom = self:Child("PanelGameSetting/imgHideBg/btnGameMainQuitRoom")
	self.btnSettingSystem = self:Child("PanelGameSetting/imgHideBg/btnSettingSystem")
	self.btnShowTips = self:Child("PanelGameSetting/imgHideBg/btnShowTips")
	self.btnMask = self:Child("PanelGameSetting/btnMask")
	self.btnSettingGame = self:Child("btnSettingGame")
	self.btnHideUp = self:Child("PanelGameSetting/imgHideBg/btnHidePanelUp")
end