//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Src/LoginGame.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGameReq")]
  public partial class LoginGameReq : global::ProtoBuf.IExtensible
  {
    public LoginGameReq() {}
    
    private int _loginType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    private string _pid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private string _userId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _machingId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"machingId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string machingId
    {
      get { return _machingId; }
      set { _machingId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _headimgUrl = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"headimgUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headimgUrl
    {
      get { return _headimgUrl; }
      set { _headimgUrl = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSimpleInfo")]
  public partial class UserSimpleInfo : global::ProtoBuf.IExtensible
  {
    public UserSimpleInfo() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private long _diamond = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGameRes")]
  public partial class LoginGameRes : global::ProtoBuf.IExtensible
  {
    public LoginGameRes() {}
    
    private long _nowTime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nowTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long nowTime
    {
      get { return _nowTime; }
      set { _nowTime = value; }
    }
    private int _offset = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.UserSimpleInfo> _userInfo = new global::System.Collections.Generic.List<proto.UserSimpleInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserSimpleInfo> userInfo
    {
      get { return _userInfo; }
    }
  
    private string _userId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}